#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := encoder_test
# SRCDIRS += components/base_nav/
include $(IDF_PATH)/make/project.mk

